# Generated by Django 5.2.8 on 2026-01-01 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOTPProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "otp_enabled",
                    models.BooleanField(
                        default=False, help_text="Whether user has enabled OTP"
                    ),
                ),
                (
                    "backup_codes_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether backup codes have been generated",
                    ),
                ),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User OTP Profile",
                "verbose_name_plural": "User OTP Profiles",
                "db_table": "mainapp_user_otp_profile",
            },
        ),
    ]
