# Generated by Django 6.0.3 on 2026-04-18 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_usertourcompletion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="Full Name")),
                (
                    "company",
                    models.CharField(max_length=160, verbose_name="Company Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Work Email")),
                ("phone", models.CharField(max_length=40, verbose_name="Phone Number")),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10"),
                            ("11-30", "11-30"),
                            ("31-50", "31-50"),
                        ],
                        max_length=16,
                        verbose_name="Company Size",
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        blank=True,
                        choices=[("engineering", "Engineering"), ("design", "Design")],
                        max_length=32,
                        verbose_name="Team",
                    ),
                ),
                (
                    "project_budget",
                    models.CharField(
                        choices=[("20000", "$20,000+"), ("50000", "$50,000+")],
                        max_length=16,
                        verbose_name="Project Budget",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ("-created_at",),
            },
        ),
    ]
