# Generated by Django 6.0.3 on 2026-06-22 20:01

import django.db.models.deletion
import encrypted_fields.fields
import mainapp.models.webhooks
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_contactsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional human-readable label for this endpoint.",
                        max_length=255,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="HTTPS URL that receives webhook payloads.",
                        max_length=2048,
                        validators=[mainapp.models.webhooks._validate_https_url],
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text='List of event types to subscribe to, or ["*"] for all events.',
                        validators=[mainapp.models.webhooks._validate_webhook_events],
                    ),
                ),
                (
                    "secret",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True,
                        help_text="Signing secret, encrypted at rest. Auto-generated on creation.",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive endpoints do not receive deliveries.",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.team"
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique event identifier (e.g. evt_<uuid>).",
                        max_length=255,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Dot-separated event type.",
                        max_length=255,
                    ),
                ),
                ("payload", models.JSONField(help_text="Full event payload envelope.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_flight", "In Flight"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this delivery is/was scheduled to run.",
                        null=True,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, help_text="When the delivery succeeded.", null=True
                    ),
                ),
                (
                    "http_status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "response_body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Truncated response body (max 4 KB).",
                        max_length=4096,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if delivery failed.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="mainapp.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery",
                "verbose_name_plural": "Webhook Deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["endpoint", "status"],
                        name="mainapp_web_endpoin_ee28ad_idx",
                    ),
                    models.Index(
                        fields=["event_id"], name="mainapp_web_event_i_cd7fcc_idx"
                    ),
                ],
            },
        ),
    ]
