# Generated by Django 6.0.3 on 2026-06-26 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_webhook_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='response_body',
            field=models.TextField(blank=True, default='', help_text='Truncated response body (max 4 KB).'),
        ),
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(db_index=True, help_text="Identifier for the kind of work (e.g. 'demo').", max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('progress_current', models.PositiveIntegerField(default=0, help_text='Current step (0-based).')),
                ('progress_total', models.PositiveIntegerField(default=0, help_text='Total steps; 0 means indeterminate.')),
                ('message', models.CharField(blank=True, default='', help_text='Human-readable progress message.', max_length=255)),
                ('result', models.JSONField(blank=True, help_text='Arbitrary result payload on success.', null=True)),
                ('error', models.TextField(blank=True, default='', help_text='Error details on failure.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='async_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Async Job',
                'verbose_name_plural': 'Async Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='mainapp_asy_owner_i_b4bbbe_idx'), models.Index(fields=['job_type'], name='mainapp_asy_job_typ_cc9756_idx')],
            },
        ),
    ]
