# Generated by Django 6.0.3 on 2026-06-26 11:22

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_async_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='previous_secret',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default=None, help_text='Previous signing secret kept during rotation overlap window.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='previous_secret_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the previous secret stops being accepted by verifiers.', null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='secret_rotated_at',
            field=models.DateTimeField(blank=True, help_text='When the signing secret was last rotated.', null=True),
        ),
    ]
