# Generated by Django 6.0.3 on 2026-06-27 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_webhook_secret_rotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("pro", "Pro"),
                    ("business", "Business"),
                    ("enterprise", "Enterprise"),
                ],
                db_index=True,
                default="free",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="BillingCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billable_type",
                    models.CharField(
                        choices=[("team", "Team"), ("user", "User")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("billable_id", models.CharField(db_index=True, max_length=64)),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("paddle", "Paddle")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "provider_customer_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Billing Customer",
                "verbose_name_plural": "Billing Customers",
                "indexes": [
                    models.Index(
                        fields=["billable_type", "billable_id"],
                        name="mainapp_bil_billabl_e0c418_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_customer_id"),
                        name="uniq_billing_customer_provider_customer",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingEventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("paddle", "Paddle")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("event_id", models.CharField(db_index=True, max_length=255)),
                ("event_type", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Billing Event Log",
                "verbose_name_plural": "Billing Event Logs",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"),
                        name="uniq_billing_event_provider_event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billable_type",
                    models.CharField(
                        choices=[("team", "Team"), ("user", "User")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("billable_id", models.CharField(db_index=True, max_length=64)),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("paddle", "Paddle")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "provider_customer_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "provider_subscription_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("provider_price_id", models.CharField(blank=True, max_length=255)),
                ("provider_product_id", models.CharField(blank=True, max_length=255)),
                ("plan_key", models.CharField(db_index=True, max_length=50)),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("paused", "Paused"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "raw_provider_status",
                    models.CharField(
                        blank=True,
                        help_text="Verbatim status string from the provider",
                        max_length=50,
                    ),
                ),
                (
                    "current_period_starts_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("current_period_ends_at", models.DateTimeField(blank=True, null=True)),
                ("trial_starts_at", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_effective_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("past_due_started_at", models.DateTimeField(blank=True, null=True)),
                ("grace_period_ends_at", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("grace_started_email_sent", models.BooleanField(default=False)),
                ("billing_disabled_email_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Billing Subscription",
                "verbose_name_plural": "Billing Subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["billable_type", "billable_id"],
                        name="mainapp_bil_billabl_61eb64_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("provider_subscription_id", ""), _negated=True
                        ),
                        fields=("provider", "provider_subscription_id"),
                        name="uniq_billing_subscription_provider_sub",
                    )
                ],
            },
        ),
    ]
