# Generated by Django 6.0.3 on 2026-06-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_team_plan_billingcustomer_billingeventlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsubscription",
            name="last_event_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
