# Generated by Django 6.0.3 on 2026-08-22 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_billingsubscription_last_event_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="deletion_requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The owner who asked for the deletion. Kept for the audit trail only.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="deletion_scheduled_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the scheduled deletion may run. Null means no deletion is pending.",
                null=True,
            ),
        ),
    ]
