# Generated by Django 6.0.8 on 2026-08-29 17:23

import mainapp.timezones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_team_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='timezone',
            field=models.CharField(default=mainapp.timezones.get_default_team_timezone, help_text='IANA time zone used for scheduling and daily caps.', max_length=64, validators=[mainapp.timezones.validate_timezone]),
        ),
    ]
