# Generated by Django 6.1.1 on 2026-09-09 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_team_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookendpoint",
            name="application",
            field=models.ForeignKey(
                blank=True,
                help_text="OAuth application the endpoint was created through, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the endpoint. Null once that user is deleted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="origin",
            field=models.CharField(
                choices=[
                    ("dashboard", "Dashboard (session)"),
                    ("api_token", "API token (PAT/JWT)"),
                    ("oauth", "OAuth application"),
                    ("legacy", "Legacy (pre-connection-identity)"),
                ],
                db_index=True,
                default="dashboard",
                help_text="How this endpoint was created (session, API token, or OAuth app).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="token_family",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="OAuth refresh-token family identifying one connection; deliveries stop when the family is revoked or expires.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_flight", "In Flight"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("disabled", "Disabled"),
                    ("redacted", "Redacted"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
