# Generated by Django 6.0.3 on 2026-06-22 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=512)),
                ('request_body_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'user', 'method', 'path'), name='unique_idempotency_key')],
            },
        ),
    ]
