# Generated by Django 6.0.3 on 2026-08-22 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_billingsubscription_last_event_at"),
        ("speedpycom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuppressedEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("hard_bounce", "Hard Bounce"),
                            ("complaint", "Complaint"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_message_id", models.CharField(max_length=255, unique=True)),
                (
                    "message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("send", "Send"),
                            ("delivery", "Delivery"),
                            ("bounce", "Bounce"),
                            ("complaint", "Complaint"),
                            ("reject", "Reject"),
                            ("delivery_delay", "Delivery Delay"),
                            ("rendering_failure", "Rendering Failure"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                ("recipient", models.EmailField(db_index=True, max_length=254)),
                (
                    "bounce_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("permanent", "Permanent"),
                            ("transient", "Transient"),
                            ("undetermined", "Undetermined"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bounce_subtype", models.CharField(blank=True, max_length=50)),
                ("diagnostic", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mainapp.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "event_type"],
                        name="speedpycom__recipie_f9afb4_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="speedpycom__event_t_7370cf_idx",
                    ),
                ],
            },
        ),
    ]
