# Generated by Django 6.1.1 on 2026-09-09 08:41

from django.db import migrations, models


def backfill_completed(apps, schema_editor):
    # Every pre-existing row was written by the old check-then-act decorator,
    # which only ever stored a finished response (response_status/body were
    # non-null). They are all COMPLETED — the AddField default of "in_progress"
    # would otherwise make a same-key retry get a 409 instead of the replay.
    IdempotencyRecord = apps.get_model("speedpycom", "IdempotencyRecord")
    IdempotencyRecord.objects.update(state="completed")


class Migration(migrations.Migration):

    dependencies = [
        ("speedpycom", "0002_suppressedemail_emailevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="idempotencyrecord",
            name="state",
            field=models.CharField(
                choices=[("in_progress", "In progress"), ("completed", "Completed")],
                default="in_progress",
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_completed, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="idempotencyrecord",
            name="response_body",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="idempotencyrecord",
            name="response_status",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
