# Generated by Django 6.0.3 on 2026-04-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usermodel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="Profile Picture",
            ),
        ),
    ]
