# Generated by Django 6.0.3 on 2026-04-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usermodel", "0002_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture_thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to="profile_pictures/thumbnails/",
                verbose_name="Profile Picture Thumbnail",
            ),
        ),
    ]
