# Generated by Django 6.0.3 on 2026-06-14 06:01

import usermodel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usermodel", "0003_user_profile_picture_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[usermodel.validators.validate_no_url],
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[usermodel.validators.validate_no_url],
                verbose_name="Last Name",
            ),
        ),
    ]
