# Generated by Django 6.0.3 on 2026-06-26 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0005_add_personal_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('token_type', models.CharField(blank=True, help_text="e.g. 'pat', 'oauth2', 'jwt', 'session'", max_length=16, verbose_name='Token type')),
                ('token_id', models.CharField(blank=True, help_text='PAT UUID or OAuth2 token PK — never the raw secret.', max_length=64, verbose_name='Token ID')),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='Scopes')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP method')),
                ('path', models.CharField(max_length=2048, verbose_name='Request path')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Status code')),
                ('ip_truncated', models.CharField(blank=True, max_length=45, verbose_name='IP (truncated)')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Request ID')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API access log',
                'verbose_name_plural': 'API access logs',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accesslog_user_ts')],
            },
        ),
    ]
